version: '3.2'

services:
  postgresql:
    build:
      context: ./postresql
      dockerfile: Dockerfile-dev
    ports:
      - "5432:5432"

  smart-alarm:
    build:
      context: ./smart_alarm
    volumes:
       - ./smart_alarm:/app
    links:
      - "postgresql:smart_alarm_postgresql_host"
    ports:
      - "8000:8000"
