version: '3.2'

services:
  postgresql:
    image: postgres:10.0-alpine
    ports:
      - "5432:5432"

  smart-alarm:
    build:
      context: ./smart_alarm
    volumes:
       - .:/app
    links:
      - "postgresql:smart_alarm_postgresql_host"